spring:
  application:
    name: creditcard-microservice
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    credit-card-issuance-queue: credit-card-issuance

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/creditcard-microservice.log

