
spring:
  application:
    name: client-microservice

server:
  port: 0 #ramdom port

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/client-microservice.log
