
spring:
  application:
    name: creditevaluator-microservice
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    credit-card-issuance-queue: credit-card-issuance
